source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

inhibit_all_warnings!

target 'isItColdOutside' do
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'UnsplasherSDK'
  pod 'SDWebImage'
end
